/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.cubuanic.coding.testapp;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

public class JavaTestAppTest {
    @Test
    public void appHasAGreeting() {
        JavaTestApp classUnderTest = new JavaTestApp();
        assertNotNull(classUnderTest.getGreeting());
    }
}
