/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.cubuanic.coding.testapp;

public class JavaTestApp {
    public String getGreeting() {
        return "Hello from Java!";
    }

    public static void main(String[] args) {
        System.out.println(new JavaTestApp().getGreeting());
    }
}
