/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cub.testapp;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class JavaTestAppTest {
    @Test
    void appHasAGreeting() {
        JavaTestApp classUnderTest = new JavaTestApp();
        assertNotNull(classUnderTest.getGreeting());
    }
}
